//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsCofidi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fact.com.mx/schema/ws", ConfigurationName="wsCofidi.FactWSFrontSoap")]
    public interface FactWSFrontSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/RequestTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsCofidi.TransactionTag RequestTransaction(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/RequestTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<wsCofidi.TransactionTag> RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SSLTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SSLTransaction(string Entity, string DataExchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SSLTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SSLTransactionAsync(string Entity, string DataExchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SecureTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SecureTransaction(string Entity, string DataExchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SecureTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SecureTransactionAsync(string Entity, string DataExchange);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class TransactionTag
    {
        
        private FactRequest requestField;
        
        private FactResponse responseField;
        
        private FactResponseData responseDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FactRequest Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FactResponse Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FactResponseData ResponseData
        {
            get
            {
                return this.responseDataField;
            }
            set
            {
                this.responseDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactRequest
    {
        
        private Transactions transactionField;
        
        private System.Guid requestorField;
        
        private string requestorNameField;
        
        private bool requestorActiveField;
        
        private string countryField;
        
        private string entityField;
        
        private System.Guid userField;
        
        private string userNameField;
        
        private System.Guid idField;
        
        private System.DateTime timeStampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Transactions Transaction
        {
            get
            {
                return this.transactionField;
            }
            set
            {
                this.transactionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid Requestor
        {
            get
            {
                return this.requestorField;
            }
            set
            {
                this.requestorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RequestorName
        {
            get
            {
                return this.requestorNameField;
            }
            set
            {
                this.requestorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool RequestorActive
        {
            get
            {
                return this.requestorActiveField;
            }
            set
            {
                this.requestorActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Guid User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Guid Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public enum Transactions
    {
        
        /// <remarks/>
        BASE,
        
        /// <remarks/>
        NO_TRANSACTION,
        
        /// <remarks/>
        CONVERT_NATIVE_XML,
        
        /// <remarks/>
        GET_MTE_BATCH,
        
        /// <remarks/>
        PROCESS_BATCH,
        
        /// <remarks/>
        SYSTEM_REQUEST,
        
        /// <remarks/>
        RECEIVE_BATCH,
        
        /// <remarks/>
        ENROLL_CERT,
        
        /// <remarks/>
        GET_XML,
        
        /// <remarks/>
        GET_HTML,
        
        /// <remarks/>
        GET_XML_AND_HTML,
        
        /// <remarks/>
        CANCEL_XML,
        
        /// <remarks/>
        MARK_XML_AS_PAID,
        
        /// <remarks/>
        MARK_XML_AS_UNPAID,
        
        /// <remarks/>
        SEARCH_BASIC,
        
        /// <remarks/>
        GET_MONTHLY_REPORT,
        
        /// <remarks/>
        GET_MONTHLY_REPORT_FOR_PROVIDER,
        
        /// <remarks/>
        GET_FOLIOS_BY_RFC,
        
        /// <remarks/>
        DOES_ASSIGNMENT_EXIST,
        
        /// <remarks/>
        CANCEL_XML_BY_INTERNAL_ID,
        
        /// <remarks/>
        ACTIVATE_ASSIGNMENT,
        
        /// <remarks/>
        COUNT_ACTIVE_ASSIGNMENTS,
        
        /// <remarks/>
        GET_DOCUMENT,
        
        /// <remarks/>
        AUTHENTICATE_USER,
        
        /// <remarks/>
        GET_ACCOUNT,
        
        /// <remarks/>
        DISTRIBUTE,
        
        /// <remarks/>
        QUEUE_FOR_DISTRIBUTION,
        
        /// <remarks/>
        GET_EFFECTIVE_RIGHTS,
        
        /// <remarks/>
        EXEC_STORED_PROC,
        
        /// <remarks/>
        GET_USER_INFO,
        
        /// <remarks/>
        RECEIVE,
        
        /// <remarks/>
        GET_PREVIEW,
        
        /// <remarks/>
        RETRIEVE_DOCUMENT,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_PAID,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_NOT_PAID,
        
        /// <remarks/>
        CANCEL_DOCUMENT,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_DELETED,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_NOT_DELETED,
        
        /// <remarks/>
        GET_ADDENDA_RECEIVERS,
        
        /// <remarks/>
        REQUEST_PASSWORD_CHANGE,
        
        /// <remarks/>
        CHANGE_DOCUMENT_SUCURSAL,
        
        /// <remarks/>
        CREATE_ACCOUNT_AS_OWNER,
        
        /// <remarks/>
        CREATE_PASSWORD,
        
        /// <remarks/>
        PASSWORD_FORGOT,
        
        /// <remarks/>
        CREATE_USER,
        
        /// <remarks/>
        INCREMENT_BUNDLE_SIZE,
        
        /// <remarks/>
        TIMBRAR,
        
        /// <remarks/>
        LOOKUP_ISSUED_INTERNAL_ID,
        
        /// <remarks/>
        VALIDATE_CERT,
        
        /// <remarks/>
        BATCH_SERIAL_OPERATIONS,
        
        /// <remarks/>
        PROCESS_LCO,
        
        /// <remarks/>
        ENROLL_THIRD_PARTY_CERT,
        
        /// <remarks/>
        CANCEL_CFDI,
        
        /// <remarks/>
        UPDATE_ACCOUNT_DATA,
        
        /// <remarks/>
        ASSIGN_ACCOUNT_REQUESTOR,
        
        /// <remarks/>
        UPDATE_USER_DATA,
        
        /// <remarks/>
        UPDATE_ADMIN_USER_DATA,
        
        /// <remarks/>
        CREATE_ADMIN_USER,
        
        /// <remarks/>
        UPSERT_GRAPHIC_REPRESENTATION,
        
        /// <remarks/>
        LOOKUP_ISSUED_BATCH_AND_SERIAL,
        
        /// <remarks/>
        CREATE_TIMBRAR_ACCOUNT,
        
        /// <remarks/>
        CREATE_TIMBRAR_ISSUER_ACCOUNT,
        
        /// <remarks/>
        LOOKUP_GUATEMALIAN_ISSUED,
        
        /// <remarks/>
        CLOSE_MONTH,
        
        /// <remarks/>
        SYSTEM_REQUEST1,
        
        /// <remarks/>
        GET_ACUSE,
        
        /// <remarks/>
        GRAPH_REQUEST,
        
        /// <remarks/>
        CANCEL_SINGLE_CFDI,
        
        /// <remarks/>
        CONFIG_REFRESH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponseData
    {
        
        private string responseData1Field;
        
        private string responseData2Field;
        
        private string responseData3Field;
        
        private wsCofidi.ArrayOfXElement responseDataSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResponseData1
        {
            get
            {
                return this.responseData1Field;
            }
            set
            {
                this.responseData1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResponseData2
        {
            get
            {
                return this.responseData2Field;
            }
            set
            {
                this.responseData2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResponseData3
        {
            get
            {
                return this.responseData3Field;
            }
            set
            {
                this.responseData3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public wsCofidi.ArrayOfXElement ResponseDataSet
        {
            get
            {
                return this.responseDataSetField;
            }
            set
            {
                this.responseDataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class BatchID
    {
        
        private string batchIdField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BatchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BatchTimeStamp
        {
            get
            {
                return this.batchTimeStampField;
            }
            set
            {
                this.batchTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BatchRequestorCountry
        {
            get
            {
                return this.batchRequestorCountryField;
            }
            set
            {
                this.batchRequestorCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BatchRequestorEntity
        {
            get
            {
                return this.batchRequestorEntityField;
            }
            set
            {
                this.batchRequestorEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BatchPosition
        {
            get
            {
                return this.batchPositionField;
            }
            set
            {
                this.batchPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class DocID
    {
        
        private string countryField;
        
        private string entityField;
        
        private string fiscalNameField;
        
        private string aYearField;
        
        private string aNumberField;
        
        private string batchField;
        
        private string serialField;
        
        private string documentGUIDField;
        
        private string issuedTimeStampField;
        
        private string enrolledTimeStampField;
        
        private string paidTimeStampField;
        
        private string cancelledTimeStampField;
        
        private string internalIDField;
        
        private string batchIDField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        private string receiverCountryField;
        
        private string receiverEntityField;
        
        private string receiverTaxIDField;
        
        private string receiverNameField;
        
        private string claveAgenteField;
        
        private string numeroDePolizaField;
        
        private string currencyField;
        
        private string totalAmountField;
        
        private string type1Field;
        
        private string type2Field;
        
        private string suggestedFileNameField;
        
        private string suggestedFileName2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FiscalName
        {
            get
            {
                return this.fiscalNameField;
            }
            set
            {
                this.fiscalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AYear
        {
            get
            {
                return this.aYearField;
            }
            set
            {
                this.aYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ANumber
        {
            get
            {
                return this.aNumberField;
            }
            set
            {
                this.aNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Batch
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Serial
        {
            get
            {
                return this.serialField;
            }
            set
            {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DocumentGUID
        {
            get
            {
                return this.documentGUIDField;
            }
            set
            {
                this.documentGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IssuedTimeStamp
        {
            get
            {
                return this.issuedTimeStampField;
            }
            set
            {
                this.issuedTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EnrolledTimeStamp
        {
            get
            {
                return this.enrolledTimeStampField;
            }
            set
            {
                this.enrolledTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaidTimeStamp
        {
            get
            {
                return this.paidTimeStampField;
            }
            set
            {
                this.paidTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CancelledTimeStamp
        {
            get
            {
                return this.cancelledTimeStampField;
            }
            set
            {
                this.cancelledTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string InternalID
        {
            get
            {
                return this.internalIDField;
            }
            set
            {
                this.internalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BatchID
        {
            get
            {
                return this.batchIDField;
            }
            set
            {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BatchTimeStamp
        {
            get
            {
                return this.batchTimeStampField;
            }
            set
            {
                this.batchTimeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BatchRequestorCountry
        {
            get
            {
                return this.batchRequestorCountryField;
            }
            set
            {
                this.batchRequestorCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BatchRequestorEntity
        {
            get
            {
                return this.batchRequestorEntityField;
            }
            set
            {
                this.batchRequestorEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string BatchPosition
        {
            get
            {
                return this.batchPositionField;
            }
            set
            {
                this.batchPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ReceiverCountry
        {
            get
            {
                return this.receiverCountryField;
            }
            set
            {
                this.receiverCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ReceiverEntity
        {
            get
            {
                return this.receiverEntityField;
            }
            set
            {
                this.receiverEntityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ReceiverTaxID
        {
            get
            {
                return this.receiverTaxIDField;
            }
            set
            {
                this.receiverTaxIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ReceiverName
        {
            get
            {
                return this.receiverNameField;
            }
            set
            {
                this.receiverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ClaveAgente
        {
            get
            {
                return this.claveAgenteField;
            }
            set
            {
                this.claveAgenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string NumeroDePoliza
        {
            get
            {
                return this.numeroDePolizaField;
            }
            set
            {
                this.numeroDePolizaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Type1
        {
            get
            {
                return this.type1Field;
            }
            set
            {
                this.type1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Type2
        {
            get
            {
                return this.type2Field;
            }
            set
            {
                this.type2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SuggestedFileName
        {
            get
            {
                return this.suggestedFileNameField;
            }
            set
            {
                this.suggestedFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string SuggestedFileName2
        {
            get
            {
                return this.suggestedFileName2Field;
            }
            set
            {
                this.suggestedFileName2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponse
    {
        
        private DocID identifierField;
        
        private BatchID batchIdentifierField;
        
        private bool resultField;
        
        private System.DateTime timeStampField;
        
        private string lastResultField;
        
        private int codeField;
        
        private string descriptionField;
        
        private string hintField;
        
        private string dataField;
        
        private string processorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocID Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BatchID BatchIdentifier
        {
            get
            {
                return this.batchIdentifierField;
            }
            set
            {
                this.batchIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime TimeStamp
        {
            get
            {
                return this.timeStampField;
            }
            set
            {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LastResult
        {
            get
            {
                return this.lastResultField;
            }
            set
            {
                this.lastResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Hint
        {
            get
            {
                return this.hintField;
            }
            set
            {
                this.hintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Processor
        {
            get
            {
                return this.processorField;
            }
            set
            {
                this.processorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface FactWSFrontSoapChannel : wsCofidi.FactWSFrontSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FactWSFrontSoapClient : System.ServiceModel.ClientBase<wsCofidi.FactWSFrontSoap>, wsCofidi.FactWSFrontSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FactWSFrontSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(FactWSFrontSoapClient.GetBindingForEndpoint(endpointConfiguration), FactWSFrontSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FactWSFrontSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FactWSFrontSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FactWSFrontSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FactWSFrontSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FactWSFrontSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public wsCofidi.TransactionTag RequestTransaction(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3)
        {
            return base.Channel.RequestTransaction(Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3);
        }
        
        public System.Threading.Tasks.Task<wsCofidi.TransactionTag> RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3)
        {
            return base.Channel.RequestTransactionAsync(Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3);
        }
        
        public string SSLTransaction(string Entity, string DataExchange)
        {
            return base.Channel.SSLTransaction(Entity, DataExchange);
        }
        
        public System.Threading.Tasks.Task<string> SSLTransactionAsync(string Entity, string DataExchange)
        {
            return base.Channel.SSLTransactionAsync(Entity, DataExchange);
        }
        
        public string SecureTransaction(string Entity, string DataExchange)
        {
            return base.Channel.SecureTransaction(Entity, DataExchange);
        }
        
        public System.Threading.Tasks.Task<string> SecureTransactionAsync(string Entity, string DataExchange)
        {
            return base.Channel.SecureTransactionAsync(Entity, DataExchange);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FactWSFrontSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FactWSFrontSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FactWSFrontSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.cofidiguatemala.com/webservicefrontfeltest/factwsfront.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.FactWSFrontSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.cofidiguatemala.com/webservicefrontfeltest/factwsfront.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FactWSFrontSoap,
            
            FactWSFrontSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
