//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 
namespace AddOns {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.gt/face2/ComplementoExportaciones/0.1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.gt/face2/ComplementoExportaciones/0.1.0", IsNullable=false)]
    public partial class Exportacion {
        
        private string nombreConsignatarioODestinatarioField;
        
        private string direccionConsignatarioODestinatarioField;
        
        private string codigoConsignatarioODestinatarioField;
        
        private string nombreCompradorField;
        
        private string direccionCompradorField;
        
        private string codigoCompradorField;
        
        private string otraReferenciaField;
        
        private INCOTERMType iNCOTERMField;
        
        private string nombreExportadorField;
        
        private string codigoExportadorField;
        
        private string versionField;
        
        public Exportacion() {
            this.versionField = "1";
        }
        
        /// <remarks/>
        public string NombreConsignatarioODestinatario {
            get {
                return this.nombreConsignatarioODestinatarioField;
            }
            set {
                this.nombreConsignatarioODestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string DireccionConsignatarioODestinatario {
            get {
                return this.direccionConsignatarioODestinatarioField;
            }
            set {
                this.direccionConsignatarioODestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoConsignatarioODestinatario {
            get {
                return this.codigoConsignatarioODestinatarioField;
            }
            set {
                this.codigoConsignatarioODestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string NombreComprador {
            get {
                return this.nombreCompradorField;
            }
            set {
                this.nombreCompradorField = value;
            }
        }
        
        /// <remarks/>
        public string DireccionComprador {
            get {
                return this.direccionCompradorField;
            }
            set {
                this.direccionCompradorField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoComprador {
            get {
                return this.codigoCompradorField;
            }
            set {
                this.codigoCompradorField = value;
            }
        }
        
        /// <remarks/>
        public string OtraReferencia {
            get {
                return this.otraReferenciaField;
            }
            set {
                this.otraReferenciaField = value;
            }
        }
        
        /// <remarks/>
        public INCOTERMType INCOTERM {
            get {
                return this.iNCOTERMField;
            }
            set {
                this.iNCOTERMField = value;
            }
        }
        
        /// <remarks/>
        public string NombreExportador {

            get {
                return this.nombreExportadorField;
            }
            set {
                this.nombreExportadorField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoExportador {
            get {
                return this.codigoExportadorField;
            }
            set {
                this.codigoExportadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.gt/face2/ComplementoExportaciones/0.1.0")]
    public enum INCOTERMType {
        
        /// <remarks/>
        EXW,
        
        /// <remarks/>
        FCA,
        
        /// <remarks/>
        FAS,
        
        /// <remarks/>
        FOB,
        
        /// <remarks/>
        CFR,
        
        /// <remarks/>
        CIF,
        
        /// <remarks/>
        CPT,
        
        /// <remarks/>
        CIP,
        
        /// <remarks/>
        DDP,
        
        /// <remarks/>
        DAP,
        
        /// <remarks/>
        DAT,
        
        /// <remarks/>
        ZZZ,
    }
}
